baseURL = "http://docs.monaca.io/"

title = "Monaca Docs"
theme = "monaca"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]
disableNavChevron = true
disableHomeIcon = true
disableLanguageSwitchingButton = false

[Languages]
[Languages.en]
languageName = "English"

[Languages.ja]
languageName = "日本語"