baseURL = "http://docs.monaca.io/"

DefaultContentLanguage = "en"

title = "Monaca Docs"

theme = "docdock"

[params]
disableNavChevron = true
disableHomeIcon = true
disableLanguageSwitchingButton = true

[Languages]
[Languages.en]

[Languages.ja]