baseURL = "http://docs.monaca.io/"


title = "Monaca Docs"

theme = "monaca"

[params]
disableNavChevron = true
disableHomeIcon = true
disableLanguageSwitchingButton = true

[Languages]
[Languages.en]
url = "/en/"

[Languages.ja]
url = "/ja/"