version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run: 
          name: install hugo
          command: go get -v github.com/gohugoio/hugo 
      - run: pip install --upgrade pip
      - run: pip install awscli --upgrade --user
      - run: npm install
      - run: npm rebuild node-sass
      - run: npm run build-sass
      - run:
          name: build hugo
          command: hugo --baseURL "http://test-hugo.s3-website-us-east-1.amazonaws.com/"
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync public s3://s.docs.monaca.io --delete
