version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get update
      - run: 
          name: install hugo
          command: sudo apt-get install hugo
      - run: npm install
      - run: npm rebuild node-sass
