version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: install hugo
          command: snap install hugo
      - run: npm install
      - run: npm rebuild node-sass
