version: 2
jobs:
  build:
    machine: true
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install hugo
          command: go get -v github.com/gohugoio/hugo 
      - run:
          name: Install pip
          command: pip install --upgrade pip
      - run: 
          name: install AWS CLI
          command: pip install awscli --upgrade --user
      - run: 
          name: Install NPM dependency
          command: npm install
      - run: 
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - run: 
          name: Run build-sass
          command: npm run build-sass
      - run:
          name: Build hugo
          command: hugo --baseURL "http://s.docs.monaca.io/"
      - save_cache:
          key: docs-{{ epoch }}
          paths:
            - ~/project/public

  deploy-stg:
    machine: true
    working_directory: ~/project
    steps:
      - restore_cache:
          keys:
            - docs
      - run:
          name: Deploy to stg 
          command: aws s3 sync ~/project/public s3://s.docs.monaca.io --delete

  deploy-prod:
    machine: true
    working_directory: ~/project
    steps:
      - restore_cache:
          keys:
            - docs
      - run:
          name: Deploy to production
          command: aws s3 sync ~/project/public s3://s.docs.monaca.io --delete

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy-stg:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build 
          filters:
            branches:
              only: production