version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: 
          name: install hugo
          command: go get -v github.com/gohugoio/hugo 
      - run: ls -la
      - run: pip install awscli --upgrade --user
      - run:
          name: build hugo
          command: hugo
      - run: npm install
      - run: npm rebuild node-sass
      - run: ls -la
      - run: pwd
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: aws s3 sync public s3://test-hugo --delete
